"""Hybrid BM25 (+ optional dense) retriever over the Unity Manual / ScriptReference mirror.

Retrieval only -- no LLM generation by design. Operational manual: AGENTS.md.
Measured quality numbers: eval_results.md (regenerated by eval_retrieval.py).

Quickstart:
    uv run python hybrid_retrieve.py --query "Rigidbody.AddForce"
    uv run python hybrid_retrieve.py --mentions MaterialPropertyBlock --text
    uv run python hybrid_retrieve.py --query-file q.txt --out hits.json   # batch
    uv run python hybrid_retrieve.py --repl          # persistent JSONL session
    uv run python hybrid_retrieve.py --build --force # rebuild after doc changes

Works from any working directory: paths resolve against this script's folder
(override with the UNITY_DOCS_ROOT env var).
"""

from __future__ import annotations

import argparse
import hashlib
import heapq
import json
import math
import os
import pickle
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import xxhash
from bs4 import BeautifulSoup
from tqdm import tqdm

from retrieval import BM25Scorer, InvertedIndex, NgramTokenizer, Searcher
from unity_tokenizer import WordTokenizer, path_terms
from doc_clean import content_root, page_title, strip_boiler

# --------------------------------------------------------------------------------------
# Paths: everything resolves against the repo root (this file's folder), optionally
# overridden by UNITY_DOCS_ROOT, so the tool works from any cwd.
# --------------------------------------------------------------------------------------

ROOT = Path(os.environ.get("UNITY_DOCS_ROOT", "")).resolve() \
    if os.environ.get("UNITY_DOCS_ROOT") else Path(__file__).resolve().parent

MANIFEST_PATH = "manifest.json"
SCHEMA_VERSION = 2


def resolve_path(p: str | Path, base: Path = ROOT) -> Path:
    """Absolute path for *p*; relative paths anchor at *base* (repo root by default)."""
    p = Path(p)
    return p if p.is_absolute() else (base / p).resolve()


def rel_source(path: str | Path) -> str:
    """Posix path relative to ROOT when possible (stable, display-friendly source ids)."""
    p = Path(path)
    try:
        return p.resolve().relative_to(ROOT).as_posix()
    except (ValueError, OSError):
        return p.as_posix()


def _norm_rel(p: str | Path) -> str:
    """Normalise a path for prefix comparison: relative-to-ROOT posix, no trailing slash."""
    s = rel_source(p)
    return s.rstrip("/")


@dataclass
class Chunk:
    chunk_id: int
    source: str
    text: str
    title: str = ""


def load_chunks_pickle(path: str) -> list[Chunk]:
    """Unpickle chunks safely regardless of how ``Chunk`` was originally pickled.

    ``--build`` run as a script used to pickle dataclasses defined in ``__main__``, so the
    stored class path could be ``__main__.Chunk``. Loading that from any other module raises
    ``AttributeError: module '__main__' has no attribute 'Chunk'``. Register the class under
    that name before unpickling so ``chunks.pkl`` stays readable from libraries, notebooks
    and the REPL.
    """
    main_mod = sys.modules.setdefault("__main__", sys.modules[__name__])
    if not hasattr(main_mod, "Chunk"):
        setattr(main_mod, "Chunk", Chunk)
    with open(path, "rb") as f:
        return pickle.load(f)


def save_chunks_pickle(chunks: list["Chunk"], path: str) -> None:
    """Pickle *chunks* to *path* with a module-stable class reference.

    When this file is run as a script, ``Chunk`` lives in ``__main__`` and a separate
    ``hybrid_retrieve`` module object may also exist; pickle rejects the alias unless the
    registered class is literally the same object. So alias the running module under the
    importable name first, then stamp ``__module__``.
    """
    mod = sys.modules[__name__]
    if getattr(mod, "Chunk", None) is not Chunk:
        mod.Chunk = Chunk
    if getattr(sys.modules.get("hybrid_retrieve"), "Chunk", None) is not Chunk:
        sys.modules["hybrid_retrieve"] = mod
    prev = Chunk.__module__
    Chunk.__module__ = "hybrid_retrieve"
    try:
        with open(path, "wb") as f:
            pickle.dump(chunks, f)
    finally:
        Chunk.__module__ = prev


def clean_html_file(path: str) -> tuple[str, str]:
    """Extract semantic text and title from a Unity doc HTML file.

    Uses the same content-root selector as dumpdoc.py and strips site chrome
    (nav bar, language selector, feedback widget) so boilerplate never enters
    the index. Returns (text, title).
    """
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        soup = BeautifulSoup(f.read(), "lxml")
    title = page_title(soup)
    root = content_root(soup)
    for tag in root(["script", "style", "nav", "footer", "header", "aside"]):
        tag.decompose()
    parts: list[str] = []
    for elem in root.find_all(["h1", "h2", "h3", "h4", "p", "pre", "code", "li", "td"]):
        text = elem.get_text(strip=True)
        if text:
            parts.append(text)
    return strip_boiler("\n".join(parts)), title


def chunk_text(text: str, max_len: int = 800, overlap: int = 120) -> list[str]:
    """Simple paragraph-based chunking with overlap."""
    paragraphs = [p.strip() for p in re.split(r"\n+", text) if p.strip()]
    chunks: list[str] = []
    current = ""
    for p in paragraphs:
        if len(current) + len(p) + 1 > max_len and current:
            chunks.append(current.strip())
            current = current[-overlap:] if overlap < len(current) else ""
        current += ("\n" if current else "") + p
    if current:
        chunks.append(current.strip())
    return chunks or [text[:max_len]]


def load_chunks(dirs: list[str], max_files: int | None = None) -> list[Chunk]:
    """Load HTML files from *dirs* (resolved against ROOT) and split into chunks.

    Sources are stored ROOT-relative posix so results are stable across machines/cwds.
    """
    files: list[Path] = []
    for d in dirs:
        root = resolve_path(d)
        files.extend(root.rglob("*.html"))
    if max_files:
        files = files[:max_files]
    chunks: list[Chunk] = []
    for path in tqdm(files, desc="Parsing HTML"):
        try:
            text, title = clean_html_file(str(path))
        except Exception:
            continue
        if len(text) < 50:
            continue
        src = rel_source(path)
        for c in chunk_text(text):
            chunks.append(Chunk(chunk_id=len(chunks), source=src, text=c, title=title))
    return chunks


def build_page_map(chunks: list["Chunk"]) -> dict[str, list[int]]:
    """normalised source -> chunk ids in document order (chunk_id order == append order)."""
    pages: dict[str, list[int]] = {}
    for c in chunks:
        pages.setdefault(rel_source(c.source), []).append(c.chunk_id)
    return pages


def render_snippet(
    chunk: "Chunk",
    chunks: list["Chunk"],
    page_map: dict[str, list[int]],
    width: int = 500,
) -> tuple[str, bool]:
    """Boilerplate-stripped snippet for *chunk*.

    Falls back to sibling chunks of the same page when stripping empties the text.
    Returns (snippet, truncated).
    """
    def clean(t: str) -> str:
        return strip_boiler(t).strip()

    text = clean(chunk.text)
    if not text:
        for cid in page_map.get(rel_source(chunk.source), []):
            if cid == chunk.chunk_id:
                continue
            text = clean(chunks[cid].text)
            if text:
                break
    return text[:width], len(text) > width


# --------------------------------------------------------------------------------------
# tokenizers
# --------------------------------------------------------------------------------------


def get_tokenizer(name: str):
    """Return the tokenizer for *name* ('word' | 'ngram')."""
    if name == "word":
        return WordTokenizer()
    if name == "ngram":
        return NgramTokenizer(n=2)
    raise ValueError(f"unknown tokenizer {name!r} (expected 'word' or 'ngram')")


def doc_tokens(chunk: "Chunk", tok, path_boost: int) -> list[str]:
    """Terms for one chunk: body text plus path/title field terms repeated *path_boost*."""
    toks = tok.tokenize(chunk.text)
    if path_boost and not isinstance(tok, NgramTokenizer):
        toks = toks + path_terms(chunk.source) * path_boost
    return toks


def build_bm25_index(
    chunks: list[Chunk],
    tokenizer=None,
    path_boost: int = 3,
) -> tuple[InvertedIndex, Searcher]:
    """Build a BM25 inverted index over *chunks*."""
    tokenizer = tokenizer or get_tokenizer("word")
    index = InvertedIndex()
    for chunk in tqdm(chunks, desc="Building BM25 index"):
        index.add_document(chunk.chunk_id, doc_tokens(chunk, tokenizer, path_boost))
    index.finalize()
    searcher = Searcher(index, tokenizer=tokenizer, fuzziness=0, min_should_match=0.6)
    return index, searcher


class Embedder:
    """Base embedder interface."""

    def embed(self, texts: list[str]) -> list[np.ndarray]:
        raise NotImplementedError


class OllamaEmbedder(Embedder):
    """Ollama dense embeddings (default: nomic-embed-text)."""

    def __init__(self, model: str = "nomic-embed-text", host: str = "http://localhost:11434"):
        import ollama

        self.model = model
        self.client = ollama.Client(host=host)
        self.dim: int | None = None

    def embed(self, texts: list[str]) -> list[np.ndarray]:
        vectors: list[np.ndarray] = []
        for t in texts:
            # Keep a reasonable length to avoid overloading the context window
            prompt = t[:4000]
            resp = self.client.embeddings(model=self.model, prompt=prompt)
            vec = np.array(resp["embedding"], dtype=np.float32)
            if self.dim is None:
                self.dim = vec.shape[0]
            vectors.append(vec)
        return vectors


class SentenceTransformerEmbedder(Embedder):
    """Fallback local embedder using sentence-transformers (requires network to download model)."""

    def __init__(self, model: str = "all-MiniLM-L6-v2"):
        from sentence_transformers import SentenceTransformer

        self.model = SentenceTransformer(model)
        self.dim = self.model.get_sentence_embedding_dimension()

    def embed(self, texts: list[str]) -> list[np.ndarray]:
        embeddings = self.model.encode(
            texts, convert_to_numpy=True, show_progress_bar=False, normalize_embeddings=False
        )
        return [np.asarray(e, dtype=np.float32) for e in embeddings]


class HashEmbedder(Embedder):
    """Deterministic local dense embedder using hashed n-gram features.

    Works fully offline. NOTE: this is a character-signature model, not a semantic one.
    On the Unity corpus it measured *worse* than pure BM25 (MRR 0.861 -> 0.754), so it is
    no longer used unless explicitly requested.
    """

    def __init__(self, dim: int = 384):
        self.dim = dim

    def _vector(self, text: str) -> np.ndarray:
        v = np.zeros(self.dim, dtype=np.float32)
        norm_text = NgramTokenizer.normalize(text)
        tokens = NgramTokenizer(n=3).tokenize(norm_text)
        for t in tokens:
            h = xxhash.xxh64(t.encode("utf-8")).intdigest()
            # Spread each token across several buckets for smoother signatures
            for i in range(min(8, self.dim)):
                idx = int((h + i * 0x9E3779B97F4A7C15) % self.dim)
                v[idx] += 1.0 if (h >> i) & 1 else -1.0
        norm = np.linalg.norm(v)
        if norm > 0:
            v /= norm
        return v

    def embed(self, texts: list[str]) -> list[np.ndarray]:
        return [self._vector(t) for t in texts]


def cosine_scores(query_emb: np.ndarray, doc_embs: list[np.ndarray]) -> list[float]:
    """Return cosine similarity scores."""
    q = query_emb / (np.linalg.norm(query_emb) + 1e-8)
    scores: list[float] = []
    for emb in doc_embs:
        e = emb / (np.linalg.norm(emb) + 1e-8)
        scores.append(float(np.dot(q, e)))
    return scores


def minmax_normalize(scores: dict[int, float]) -> dict[int, float]:
    vals = list(scores.values())
    if not vals:
        return scores
    min_v, max_v = min(vals), max(vals)
    if max_v == min_v:
        return {k: 1.0 for k in scores}
    return {k: (v - min_v) / (max_v - min_v) for k, v in scores.items()}


def reciprocal_rank(rank: int) -> float:
    return 1.0 / (rank + 60)


def dedupe_by_source(
    ranked: list[int],
    chunks: list["Chunk"],
    per_file: int | None = 1,
) -> list[int]:
    """Keep at most *per_file* chunks per source document, preserving score order."""
    if not per_file:
        return ranked
    seen: dict[str, int] = {}
    out: list[int] = []
    for d in ranked:
        src = Path(str(chunks[d].source)).as_posix()
        n = seen.get(src, 0)
        if n >= per_file:
            continue
        seen[src] = n + 1
        out.append(d)
    return out


def hybrid_search(
    query: str,
    chunks: list[Chunk],
    searcher: Searcher,
    embedder: Embedder | None = None,
    bm25_k: int = 50,
    final_k: int = 5,
    alpha: float = 1.0,
    per_file: int | None = 1,
) -> list[tuple[Chunk, float, float, float]]:
    """BM25 candidate retrieval + optional dense re-rank + linear fusion.

    Returns list of (chunk, fused_score, bm25_norm, dense_norm).
    """
    bm25_results = searcher.search(query, top_k=bm25_k)
    if not bm25_results:
        return []

    bm25_ids = [doc_id for doc_id, _ in bm25_results]
    bm25_scores = {doc_id: score for doc_id, score in bm25_results}
    bm25_norm = minmax_normalize(bm25_scores)

    dense_scores: dict[int, float] = {}
    dense_norm: dict[int, float] = {}
    if embedder is not None and alpha < 1.0:
        candidate_texts = [chunks[i].text for i in bm25_ids]
        query_emb = embedder.embed([query])[0]
        doc_embs = embedder.embed(candidate_texts)
        dense_scores = {i: score for i, score in zip(bm25_ids, cosine_scores(query_emb, doc_embs))}
        dense_norm = minmax_normalize(dense_scores)

    fused: dict[int, float] = {}
    bm25_ranks = {doc_id: rank for rank, doc_id in enumerate(bm25_ids)}
    dense_ranks: dict[int, int] = {}
    if dense_scores:
        dense_order = sorted(bm25_ids, key=lambda x: dense_scores[x], reverse=True)
        dense_ranks = {doc_id: rank for rank, doc_id in enumerate(dense_order)}

    for doc_id in bm25_ids:
        d_norm = dense_norm.get(doc_id, 0.0)
        fused[doc_id] = (
            alpha * bm25_norm[doc_id]
            + (1.0 - alpha) * d_norm
            + 0.01 * reciprocal_rank(bm25_ranks[doc_id])
            + (0.01 * reciprocal_rank(dense_ranks[doc_id]) if dense_ranks else 0.0)
        )

    ranked = heapq.nlargest(len(fused), fused, key=lambda x: (fused[x], -x))
    ranked = dedupe_by_source(ranked, chunks, per_file)[:final_k]
    return [(chunks[i], fused[i], bm25_norm[i], dense_norm.get(i, 0.0)) for i in ranked]


def find_mentions(
    chunks: list["Chunk"],
    term: str,
    *,
    ignore_case: bool = True,
    limit_files: int = 60,
    context: int = 0,
    dirs: tuple[str, ...] | None = None,
) -> list[dict]:
    """Enumerate every document that literally contains *term*, with occurrence counts.

    This is the "which pages mention this symbol at all?" query. BM25 cannot answer it: a
    page that mentions a term once ranks indistinguishably from one that mentions it fifty
    times, and high-frequency generic terms drown the signal. During real doc research this
    enumeration (plus a corpus-wide grep) is what actually finds the authoritative pages.
    """
    needle = term.lower() if ignore_case else term
    per_file: dict[str, int] = {}
    samples: dict[str, str] = {}
    for c in chunks:
        src = str(c.source).replace("\\", "/")
        if dirs and not src.startswith(dirs):
            continue
        hay = c.text.lower() if ignore_case else c.text
        n = hay.count(needle)
        if not n:
            continue
        per_file[src] = per_file.get(src, 0) + n
        if context and src not in samples:
            i = hay.find(needle)
            lo = max(0, i - context)
            samples[src] = re.sub(r"\s+", " ", c.text[lo:i + len(term) + context])
    ranked = heapq.nlargest(limit_files, per_file, key=lambda s: (per_file[s], s))
    return [{"source": s, "count": per_file[s],
             **({"context": samples[s]} if context and s in samples else {})} for s in ranked]


def get_embedder(prefer: str = "none", ollama_model: str = "nomic-embed-text") -> Embedder | None:
    """Return an embedder for *prefer*; ``none`` disables dense re-ranking (the default).

    Falls back to ``None`` (BM25-only) rather than the hash embedder when a requested
    backend is unreachable, because the hash signature embedder measurably degrades
    ranking on this corpus.
    """
    if prefer in ("none", "", None):
        return None
    if prefer == "st":
        return SentenceTransformerEmbedder()
    if prefer == "hash":
        print("[embedder] 'hash' is a character-signature model and hurts ranking here; "
              "prefer 'none', 'ollama' or 'st'.", file=sys.stderr)
        return HashEmbedder()
    if prefer == "ollama":
        try:
            emb = OllamaEmbedder(model=ollama_model)
            emb.embed(["hello"])  # connectivity check
            print(f"[embedder] Using Ollama model '{ollama_model}'", file=sys.stderr)
            return emb
        except Exception as exc:
            print(f"[embedder] Ollama unavailable ({exc}); falling back to BM25-only",
                  file=sys.stderr)
    return None


# --------------------------------------------------------------------------------------
# Build manifest: one manifest.json at ROOT, keyed by index file name, so a stale or
# mismatched (index, chunks) pair is caught loudly instead of silently mis-ranking.
# --------------------------------------------------------------------------------------


def _sha1_8(path: Path) -> str:
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for blk in iter(lambda: f.read(1 << 20), b""):
            h.update(blk)
    return h.hexdigest()[:8]


def _n_docs(index: InvertedIndex) -> int:
    try:
        return len(index._doc_lengths)
    except Exception:
        return -1


def write_manifest(
    index_path: Path,
    chunks_path: Path,
    n_chunks: int,
    n_docs: int,
    tokenizer: str,
    path_boost: int,
) -> None:
    """Record build metadata for *index_path* in ROOT/manifest.json."""
    mf = resolve_path(MANIFEST_PATH)
    data = {"indices": {}}
    if mf.exists():
        try:
            data = json.loads(mf.read_text(encoding="utf-8"))
            data.setdefault("indices", {})
        except Exception:
            pass
    entry = {
        "built_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "tokenizer": tokenizer,
        "path_boost": path_boost,
        "n_chunks": n_chunks,
        "n_docs_indexed": n_docs,
        "chunks_path": rel_source(chunks_path),
        "chunks_size": chunks_path.stat().st_size,
        "chunks_sha1_8": _sha1_8(chunks_path),
        "index_size": index_path.stat().st_size,
        "index_sha1_8": _sha1_8(index_path),
    }
    data["indices"][index_path.name] = entry
    mf.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print(f"updated {mf.name} entry for {index_path.name}", file=sys.stderr)


def check_manifest(
    index_path: Path,
    chunks_path: Path,
    chunks: list["Chunk"],
    verify: bool = False,
) -> None:
    """Warn (stderr, non-fatal) when the loaded artefacts look stale or mismatched.

    Default check is size-based (cheap); ``verify=True`` also compares sha1.
    """
    mf = resolve_path(MANIFEST_PATH)
    warn: list[str] = []
    if not mf.exists():
        warn.append(f"no {MANIFEST_PATH} at {mf} — artefacts predate manifest tracking; "
                    f"rebuild with --build --force to enable staleness checks")
    else:
        try:
            entry = json.loads(mf.read_text(encoding="utf-8"))["indices"].get(index_path.name)
        except Exception as exc:
            entry = None
            warn.append(f"could not parse {MANIFEST_PATH}: {exc}")
        if entry is None and mf.exists():
            warn.append(f"{MANIFEST_PATH} has no entry for {index_path.name} "
                        f"(built by another tool?); rebuild with --build --force")
        elif entry is not None:
            if entry.get("n_chunks") != len(chunks):
                warn.append(f"manifest says {entry.get('n_chunks')} chunks but "
                            f"{chunks_path.name} loaded {len(chunks)} — chunks/index mismatch")
            if entry.get("chunks_path") and rel_source(chunks_path) != entry["chunks_path"]:
                warn.append(f"chunks file is {rel_source(chunks_path)} but manifest expects "
                            f"{entry['chunks_path']}")
            if entry.get("index_size") != index_path.stat().st_size:
                warn.append(f"{index_path.name} size changed since build "
                            f"({entry.get('index_size')} -> {index_path.stat().st_size})")
            if entry.get("chunks_size") != chunks_path.stat().st_size:
                warn.append(f"{chunks_path.name} size changed since build "
                            f"({entry.get('chunks_size')} -> {chunks_path.stat().st_size})")
            if verify:
                if entry.get("index_sha1_8") != _sha1_8(index_path):
                    warn.append(f"{index_path.name} sha1 mismatch vs manifest")
                if entry.get("chunks_sha1_8") != _sha1_8(chunks_path):
                    warn.append(f"{chunks_path.name} sha1 mismatch vs manifest")
    for w in warn:
        print(f"[manifest] WARNING: {w}", file=sys.stderr)


DEFAULT_CONFIG_PATH = "retriever_config.json"

# Defaults applied when retriever_config.json omits a key.
DEFAULTS: dict = {
    "tokenizer": "word",
    "path_boost": 3,
    "fuzziness": 0,
    "min_should_match": 0.6,
    "per_file": 1,
    "embedder": "none",
    "ollama_model": "nomic-embed-text",
    "bm25_k": 200,
    "final_k": 8,
    "alpha": 1.0,
    "dirs": ["Manual", "ScriptReference"],
    "index_path": "index_word.pkl",
    "ngram_index_path": "index.pkl",
    "chunks_path": "chunks.pkl",
}


def find_config(path: str) -> Path:
    """Locate the config file: cwd first (explicit override), then the repo root."""
    p = Path(path)
    if p.is_absolute() and p.exists():
        return p
    if p.exists():
        return p.resolve()
    alt = ROOT / path
    return alt.resolve() if alt.exists() else p.resolve()


def load_config(path: str = DEFAULT_CONFIG_PATH) -> tuple[dict, Path]:
    """Load JSON config merged over DEFAULTS. Returns (config, config_file_path)."""
    cfg = dict(DEFAULTS)
    p = find_config(path)
    if p.exists():
        with open(p, "r", encoding="utf-8") as f:
            cfg.update(json.load(f))
    return cfg, p


def resolve_index_path(args, cfg: dict) -> Path:
    """Pick the index file matching the selected tokenizer unless one was given explicitly."""
    if args.index_path_explicit:
        return resolve_path(args.index_path)
    if args.tokenizer == "ngram" or cfg.get("tokenizer") == "ngram":
        return resolve_path(cfg.get("ngram_index_path") or cfg["index_path"])
    return resolve_path(cfg["index_path"])


def build_searcher(index: InvertedIndex, tokenizer, args) -> Searcher:
    """Wrap *index* in a Searcher using the CLI's scoring parameters."""
    return Searcher(
        index,
        tokenizer=tokenizer,
        fuzziness=args.fuzziness,
        min_should_match=args.min_should_match,
    )


def read_queries(args) -> list[str]:
    """Collect queries from (repeatable) --query and/or --query-file."""
    out: list[str] = []
    for q in args.query or []:
        if q and q.strip():
            out.append(q.strip())
    if args.query_file:
        for ln in Path(args.query_file).read_text(encoding="utf-8").splitlines():
            ln = ln.strip()
            if ln and not ln.startswith("#"):
                out.append(ln)
    return out


def explain_terms(searcher: Searcher, tokenizer, query: str, limit: int = 12) -> list[dict]:
    """Report which query terms the index actually knows, with document frequencies."""
    raw = [t for t in dict.fromkeys(tokenizer.tokenize(query))]
    info = []
    for t in raw[:limit]:
        try:
            df = searcher.index.doc_freq(t)
        except Exception:
            df = -1
        info.append({"term": t, "df": df, "in_index": df > 0})
    return info


# --------------------------------------------------------------------------------------
# Session: everything needed to serve queries/mentions/reads, loaded once.
# --------------------------------------------------------------------------------------


class Session:
    """Loaded retriever state shared by CLI query mode, --repl and mcp_server.py."""

    def __init__(self, args, config: dict, embedder: "Embedder | None" = None):
        self.args = args
        self.config = config
        self.index_path = resolve_index_path(args, config)
        self.chunks_path = resolve_path(args.chunks_path)
        missing = [p for p in (self.chunks_path, self.index_path) if not p.exists()]
        if missing:
            raise FileNotFoundError(
                "artefact not found: " + ", ".join(str(m) for m in missing) +
                f"\n  cwd: {Path.cwd()}\n  repo root: {ROOT}\n"
                f"Paths resolve against the repo root — run from there, set "
                f"UNITY_DOCS_ROOT, or rebuild with --build (takes a few minutes)."
            )
        t0 = time.time()
        self.chunks: list[Chunk] = load_chunks_pickle(str(self.chunks_path))
        self.index = InvertedIndex()
        self.index.load(str(self.index_path))
        self.tokenizer = get_tokenizer(args.tokenizer)
        self.searcher = build_searcher(self.index, self.tokenizer, args)
        self.page_map = build_page_map(self.chunks)
        self.load_s = time.time() - t0
        check_manifest(self.index_path, self.chunks_path, self.chunks,
                       verify=getattr(args, "verify", False))
        print(f"[session] index={self.index_path.name} tokenizer={args.tokenizer} "
              f"chunks={len(self.chunks)} loaded in {self.load_s:.1f}s", file=sys.stderr)
        self.embedder = embedder if embedder is not None else get_embedder(
            prefer=args.embedder, ollama_model=args.ollama_model)

    # -- queries -----------------------------------------------------------------

    def query(self, q: str, final_k: int | None = None, bm25_k: int | None = None,
              alpha: float | None = None, per_file: int | None = None,
              explain: bool = False, dump: int = 0, context: int = 0,
              snippet_width: int = 500) -> dict:
        """One ranked query. Returns a schema-v2 per-query object."""
        a = self.args
        results = hybrid_search(
            q, self.chunks, self.searcher, self.embedder,
            bm25_k=bm25_k if bm25_k is not None else a.bm25_k,
            final_k=final_k if final_k is not None else a.final_k,
            alpha=alpha if alpha is not None else a.alpha,
            per_file=(per_file if per_file is not None else a.per_file) or None,
        )
        hits = [self._hit_payload(c, f, b, d, context, snippet_width)
                for c, f, b, d in results]
        if dump:
            self._attach_dumps(hits, dump)
        out: dict = {"query": q, "hits": hits}
        if explain:
            out["explain"] = explain_terms(self.searcher, self.tokenizer, q)
        if not hits:
            out["hint"] = ("0 results. Try: 'explain' (are the query terms indexed?), "
                           "--mentions TERM (enumerate literal occurrences), or a "
                           "shorter identifier-only query.")
            print(f"[query] 0 hits for {q!r}. Hint: use --explain to see which terms "
                  f"are in the index, or --mentions TERM to enumerate literal matches.",
                  file=sys.stderr)
        return out

    def _hit_payload(self, chunk: Chunk, fused: float, bnorm: float, dnorm: float,
                     context: int = 0, snippet_width: int = 500) -> dict:
        src = rel_source(chunk.source)
        ids = self.page_map.get(src, [])
        try:
            chunk_index = ids.index(chunk.chunk_id)
        except ValueError:
            chunk_index = -1
        snippet, truncated = render_snippet(chunk, self.chunks, self.page_map,
                                            width=snippet_width)
        title = getattr(chunk, "title", "") or Path(src).stem
        doc_type = src.split("/", 1)[0] if src.split("/", 1)[0] in ("Manual", "ScriptReference") else ""
        item: dict = {
            "source": src,
            "title": title,
            "doc_type": doc_type,
            "chunk_id": chunk.chunk_id,
            "chunk_index": chunk_index,
            "n_chunks_in_page": len(ids),
            "fused_score": round(fused, 6),
            "bm25_norm": round(bnorm, 6),
            "dense_norm": round(dnorm, 6),
            "text": snippet,
            "snippet_truncated": truncated,
            "page_text_chars": sum(len(self.chunks[i].text) for i in ids),
            "read_more": f"uv run python dumpdoc.py {src}",
        }
        if context and ids:
            lo = max(0, chunk_index - context)
            hi = min(len(ids), chunk_index + context + 1)
            ctx = []
            for pos in range(lo, hi):
                if pos == chunk_index:
                    continue
                cid = ids[pos]
                csnip, _ = render_snippet(self.chunks[cid], self.chunks, self.page_map,
                                          width=snippet_width)
                ctx.append({"chunk_id": cid, "chunk_index": pos,
                            "context_of": chunk.chunk_id, "text": csnip})
            item["context"] = ctx
        return item

    def _attach_dumps(self, hits: list[dict], dump: int) -> None:
        """Inline full page markdown (dumpdoc.py) for the top *dump* distinct sources."""
        import dumpdoc
        seen: set[str] = set()
        for h in hits:
            if len(seen) >= dump:
                break
            src = h["source"]
            if src in seen:
                continue
            seen.add(src)
            try:
                h["page_markdown"] = dumpdoc.dump(str(resolve_path(src)), heading=False)
            except Exception as exc:
                h["page_markdown_error"] = str(exc)

    # -- mentions / reads ----------------------------------------------------------

    def mentions(self, term: str, limit: int = 60, context: int = 0,
                 dirs: Iterable[str] | None = None) -> dict:
        dirs_n = tuple(_norm_rel(d) for d in dirs) if dirs else None
        return {term: find_mentions(self.chunks, term, limit_files=limit,
                                    context=context, dirs=dirs_n)}

    def read(self, source: str, max_chars: int | None = None) -> dict:
        """Full markdown for one doc page (the 'read_more' action)."""
        import dumpdoc
        path = resolve_path(source)
        if not path.exists():
            return {"source": source, "error": f"not found: {path}"}
        md = dumpdoc.dump(str(path), heading=False)
        out = {"source": rel_source(path), "chars": len(md)}
        if max_chars and len(md) > max_chars:
            out["markdown"] = md[:max_chars]
            out["truncated"] = True
        else:
            out["markdown"] = md
        return out


# --------------------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    # Load defaults from retriever_config.json first; CLI args override them.
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument("--config", default=DEFAULT_CONFIG_PATH)
    known, _ = pre.parse_known_args(argv)
    config, config_path = load_config(known.config)

    parser = argparse.ArgumentParser(
        description="Hybrid BM25 + dense retrieve over Unity docs (retrieval only, no generation)",
        epilog="Scores are relative ranking signals, not probabilities — fused_score may "
               "exceed 1.0. Snippets are stripped ~500-char previews; follow each hit's "
               "read_more command (or --dump) for the full page. Paths resolve against "
               "the repo root (UNITY_DOCS_ROOT override), so any cwd works.",
    )
    parser.add_argument("--config", default=DEFAULT_CONFIG_PATH, help="Path to JSON config file")
    parser.add_argument("--dirs", nargs="+", default=config.get("dirs"))
    parser.add_argument("--max-files", type=int, default=config.get("max_files", None),
                        help="Limit number of HTML files for quick tests")
    parser.add_argument("--build", action="store_true", help="Build and save the BM25 index")
    parser.add_argument("--force", action="store_true",
                        help="Allow --build to overwrite existing artefacts (required with --max-files)")
    parser.add_argument("--query", action="append", default=None,
                        help="Query string; repeatable — batching in one process is much "
                             "faster than one process per query (index load ~5 s)")
    parser.add_argument("--query-file", default=None,
                        help="File of queries (one per line, '#' comments) - loads the index once")
    parser.add_argument("--repl", action="store_true",
                        help="Persistent session: read JSON requests on stdin "
                             "({'query':...}|{'mentions':...}|{'read':...}), write one JSON "
                             "result per line on stdout. Index loads once.")
    parser.add_argument("--compat", choices=["v1", "v2"], default="v2",
                        help="Output schema: v2 (default, rich hits + _meta) or legacy v1")
    parser.add_argument("--dump", type=int, default=0, metavar="N",
                        help="Inline full page markdown for the top N distinct sources per query")
    parser.add_argument("--context", type=int, default=0, metavar="N",
                        help="Include N neighbour chunks around each hit")
    parser.add_argument("--snippet-width", type=int, default=500,
                        help="Max chars of each hit snippet (boilerplate-stripped)")
    parser.add_argument("--verify", action="store_true",
                        help="Full sha1 manifest check (default: size-based, cheaper)")
    parser.add_argument("--tokenizer", choices=["word", "ngram"], default=config.get("tokenizer", "word"),
                        help="Term model: 'word' (identifier-aware, default) or 'ngram' (legacy)")
    parser.add_argument("--path-boost", type=int, default=config.get("path_boost", 3),
                        help="Repeat doc path/title field terms N times when building (0 disables)")
    parser.add_argument("--fuzziness", default=config.get("fuzziness", 0),
                        help="0 disables fuzzy term expansion (recommended); 'AUTO' is the legacy behaviour")
    parser.add_argument("--min-should-match", type=float,
                        default=config.get("min_should_match", 0.6))
    parser.add_argument("--per-file", type=int, default=config.get("per_file", 1),
                        help="Max chunks per source document in the output (0 = no cap)")
    parser.add_argument("--index-path", default=config["index_path"], help="Index file to load/save")
    parser.add_argument("--chunks-path", default=config["chunks_path"], help="Chunk metadata file")
    parser.add_argument("--bm25-k", type=int, default=config.get("bm25_k", 200),
                        help="BM25 candidates to consider")
    parser.add_argument("--final-k", type=int, default=config.get("final_k", 8))
    parser.add_argument("--alpha", type=float, default=config.get("alpha", 1.0),
                        help="BM25 weight in the fused score (1-alpha is dense weight)")
    parser.add_argument("--embedder", choices=["ollama", "st", "hash", "none"],
                        default=config.get("embedder", "none"))
    parser.add_argument("--ollama-model", default=config.get("ollama_model", "nomic-embed-text"))
    parser.add_argument("--explain", action="store_true",
                        help="With --query: include per-term document frequencies (works "
                             "for any number of queries)")
    parser.add_argument("--mentions", default=None, metavar="TERM",
                        help="List every document literally containing TERM, with counts "
                             "(answers 'which pages mention this symbol at all?'). "
                             "Cannot be combined with --query.")
    parser.add_argument("--mentions-context", type=int, default=0,
                        help="With --mentions: capture N chars of surrounding text per file")
    parser.add_argument("--mentions-limit", type=int, default=60)
    parser.add_argument("--out", default=None, help="Write JSON results to this file "
                        "(relative paths resolve against the current directory)")
    parser.add_argument("--text", action="store_true", help="Print compact human-readable output")
    parser.add_argument("--legacy", action="store_true",
                        help="Force the legacy chunks.pkl/index_word.pkl engine")
    parser.add_argument("--rag", action="store_true",
                        help="Force the RAG engine even if its index is still "
                             "partial (default auto-selects by coverage)")
    args = parser.parse_args(argv)
    args.index_path_explicit = any(
        a.startswith("--index-path") for a in (argv if argv is not None else sys.argv[1:])
    )

    if not args.legacy and not args.build and not args.repl:
        # Default path: delegate to the RAG engine, but only once its index is
        # built AND covers essentially the whole mirror. While `rag.py compile`
        # is still working through the corpus, the legacy artefacts below cover
        # every page and the RAG index would silently retrieve from a subset.
        # --legacy forces this file's original engine; --rag forces the new one.
        from rag.compile import load_rag_config
        from rag.search.engine_select import choose_engine
        rag_cfg = load_rag_config()
        engine_name, status = choose_engine(
            rag_cfg, prefer="rag" if getattr(args, "rag", False) else None)
        if engine_name != "rag":
            if status.get("nothing_built"):
                print(f"[engine] no index built in this checkout: RAG index "
                      f"{status['reason']}; legacy missing "
                      f"{', '.join(status['legacy']['missing'])}. Build with "
                      f"`rag.py compile --provider <cfg> --no-thinking`, or "
                      f"`hybrid_retrieve.py --build --force` for the legacy index.",
                      file=sys.stderr)
            else:
                print(f"[engine] using LEGACY index: RAG index {status['reason']}. "
                      f"Rebuild with `rag.py compile` (then --steps index) to switch.",
                      file=sys.stderr)
        else:
            from rag.cli.search_cmd import run_search
            # Pass every legacy flag through. SA-6 requires "keep every old flag
            # working", and --mentions-context / --mentions-limit / --out /
            # --snippet-width were previously accepted-then-silently-dropped, which
            # is worse than erroring: the output just looks plausible.
            return run_search(
                queries=args.query or [], query_file=args.query_file,
                k=args.final_k, mentions=args.mentions,
                mentions_limit=args.mentions_limit,
                mentions_context=args.mentions_context,
                explain=args.explain, text=args.text, out=args.out,
                snippet_width=args.snippet_width)

    if isinstance(args.fuzziness, str) and args.fuzziness != "AUTO":
        try:
            args.fuzziness = int(args.fuzziness)
        except ValueError:
            pass

    if args.build:
        if args.max_files and not args.force:
            raise SystemExit(
                f"refusing --build --max-files {args.max_files}: this would overwrite "
                f"{args.chunks_path} (currently the full corpus) with a partial set.\n"
                f"Pass --force, or redirect both artefacts, e.g.\n"
                f"  --build --max-files 3000 --chunks-path chunks_smoke.pkl "
                f"--index-path index_smoke.pkl --force"
            )
        chunks = load_chunks(args.dirs, max_files=args.max_files)
        print(f"Loaded {len(chunks)} chunks from {[str(resolve_path(d)) for d in args.dirs]}",
              file=sys.stderr)
        tok = get_tokenizer(args.tokenizer)
        index, searcher = build_bm25_index(chunks, tok, args.path_boost)
        chunks_path = resolve_path(args.chunks_path)
        save_chunks_pickle(chunks, str(chunks_path))
        out_index = (resolve_path(args.index_path) if args.index_path_explicit else
                     resolve_path(config["ngram_index_path"] if args.tokenizer == "ngram"
                                  else config["index_path"]))
        index.save(str(out_index))
        write_manifest(out_index, chunks_path, len(chunks), _n_docs(index),
                       args.tokenizer, args.path_boost)
        print(f"Saved index to {out_index} and chunks to {chunks_path}", file=sys.stderr)

    queries = read_queries(args)

    if args.mentions and queries:
        raise SystemExit("--mentions cannot be combined with --query/--query-file: "
                         "they are different modes (enumeration vs ranking). "
                         "Run them as two separate invocations, or use --repl.")

    if args.mentions:
        chunks_path = resolve_path(args.chunks_path)
        if not chunks_path.exists():
            print(f"artefact not found: {chunks_path}\n  cwd: {Path.cwd()}\n"
                  f"  repo root: {ROOT}\nPaths resolve against the repo root — run from "
                  f"there, set UNITY_DOCS_ROOT, or rebuild with --build.", file=sys.stderr)
            return 1
        chunks = load_chunks_pickle(str(chunks_path))
        res = find_mentions(
            chunks, args.mentions,
            limit_files=args.mentions_limit,
            context=args.mentions_context,
            dirs=tuple(_norm_rel(d) for d in args.dirs) if args.dirs else None,
        )
        if not res:
            print(f"[mentions] 0 files contain {args.mentions!r}. The match is literal "
                  f"(case-insensitive) — check spelling, or try --query for ranked search.",
                  file=sys.stderr)
        out = json.dumps({args.mentions: res}, ensure_ascii=False, indent=2)
        if args.out:
            Path(args.out).write_text(out, encoding="utf-8")
            print(f"wrote {args.out}", file=sys.stderr)
        if args.text:
            print(f"# {args.mentions}: {len(res)} files")
            for r in res:
                print(f"  {r['count']:>4}  {r['source']}")
        else:
            print(out)
        return 0

    if args.repl:
        return repl_loop(args, config)

    if queries:
        try:
            session = Session(args, config)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            return 1
        t0 = time.time()
        per_query = [session.query(q, explain=args.explain, dump=args.dump,
                                   context=args.context,
                                   snippet_width=args.snippet_width)
                     for q in queries]

        if args.compat == "v1":
            # legacy shape: {query: [hits]} (single query: bare list), legacy hit fields
            legacy: dict[str, list[dict]] = {}
            for q, pq in zip(queries, per_query):
                legacy[q] = [{
                    "source": h["source"],
                    "fused_score": h["fused_score"],
                    "bm25_norm": h["bm25_norm"],
                    "dense_norm": h["dense_norm"],
                    "text": h["text"],
                } for h in pq["hits"]]
            payload = legacy if len(queries) > 1 else legacy[queries[0]]
        else:
            payload = {
                "_meta": {
                    "schema": SCHEMA_VERSION,
                    "index": str(session.index_path),
                    "tokenizer": args.tokenizer,
                    "chunks": len(session.chunks),
                    "embedder": args.embedder,
                    "score_note": "relative ranking signal, not a probability; "
                                  "fused_score may exceed 1.0",
                    "elapsed_s": round(time.time() - t0, 3),
                },
                "results": per_query,
            }
        out = json.dumps(payload, ensure_ascii=False, indent=2)
        if args.out:
            Path(args.out).write_text(out, encoding="utf-8")
            print(f"wrote {args.out}", file=sys.stderr)
        if args.text:
            for pq in per_query:
                print(f"\n### {pq['query']}")
                if pq.get("explain"):
                    known = [t["term"] for t in pq["explain"] if t["in_index"]]
                    print(f"  terms in index: {len(known)}/{len(pq['explain'])} {known}")
                for h in pq["hits"]:
                    print(f"  {h['fused_score']:<9.4f} {h['title']}  ({h['source']})")
                    print(f"            {h['text'][:160]}")
        else:
            print(out)

    return 0


def repl_loop(args, config: dict) -> int:
    """Persistent JSONL session: one JSON request per stdin line, one JSON per stdout line.

    Requests:
      {"query": "...", "final_k": 5, "explain": true, "dump": 1, "context": 1, ...}
      {"mentions": "TERM", "limit": 60, "context": 80}
      {"read": "ScriptReference/Rigidbody.AddForce.html", "max_chars": 20000}
    Responses are schema-v2 objects, or {"error": ...} for bad requests.
    """
    try:
        session = Session(args, config)
    except FileNotFoundError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print("[repl] ready — JSON requests on stdin, one JSON response per line",
          file=sys.stderr, flush=True)
    for line in sys.stdin:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            req = json.loads(line)
        except json.JSONDecodeError as exc:
            print(json.dumps({"error": f"invalid JSON: {exc}"}), flush=True)
            continue
        try:
            if "query" in req:
                resp = session.query(
                    str(req["query"]),
                    final_k=req.get("final_k"), bm25_k=req.get("bm25_k"),
                    alpha=req.get("alpha"), per_file=req.get("per_file"),
                    explain=bool(req.get("explain", False)),
                    dump=int(req.get("dump", 0)), context=int(req.get("context", 0)),
                    snippet_width=int(req.get("snippet_width", 500)),
                )
                resp["_meta"] = {"schema": SCHEMA_VERSION}
            elif "mentions" in req:
                resp = session.mentions(str(req["mentions"]),
                                        limit=int(req.get("limit", 60)),
                                        context=int(req.get("context", 0)),
                                        dirs=req.get("dirs"))
            elif "read" in req:
                resp = session.read(str(req["read"]), max_chars=req.get("max_chars"))
            else:
                resp = {"error": "request must contain one of: query, mentions, read"}
        except Exception as exc:  # keep the session alive on per-request failures
            resp = {"error": f"{type(exc).__name__}: {exc}"}
        print(json.dumps(resp, ensure_ascii=False), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
